name: Check

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  check-code-style:
#    name: Code Style
#    uses: playframework/.github/.github/workflows/cmd.yml@v2
#    with:
#      cmd: sbt validateCode

  tests:
    name: Tests
#    needs: # Waiting more lightweight checks
#      - "check-code-style"
    uses: playframework/.github/.github/workflows/cmd.yml@v2
    with:
      java: 11, 8
      scala: 2.13.8
      cmd: |
        # sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get -qq update && sudo apt-get install -y libsodium-dev # for secure session examples
        ./test.sh

  finish:
    name: Finish
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v2
